name: Regenerate README file

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - 'features/**'
      - 'README.md'

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:

  regenerate-readme: #----------------------------------------------------------
    name: Regenerate README.md file
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'wp-cli' && ! contains(fromJson('[".github", "wp-cli", "wp-cli-bundle", "wp-super-cache-cli", "php-cli-tools", "wp-config-transformer"]'), github.event.repository.name) }}
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up PHP envirnoment
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check existence of composer.json file
        id: check_composer_file
        uses: andstor/file-existence-action@v2
        with:
          files: "composer.json"

      - name: Install Composer dependencies & cache dependencies
        if: steps.check_composer_file.outputs.files_exists == 'true'
        uses: "ramsey/composer-install@v2"
        env:
          COMPOSER_ROOT_VERSION: dev-${{ github.event.repository.default_branch }}

      - name: Configure git user
        run: |
          git config --global user.email "alain.schlesser@gmail.com"
          git config --global user.name "Alain Schlesser"

      - name: Check if remote branch exists
        run: echo "REMOTE_BRANCH_EXISTS=$([[ -z $(git ls-remote --heads origin regenerate-readme) ]] && echo "0" || echo "1")" >> $GITHUB_ENV

      - name: Create branch to base pull request on
        if: env.REMOTE_BRANCH_EXISTS == 0
        run: |
          git checkout -b regenerate-readme

      - name: Fetch existing branch to add commits to
        if: env.REMOTE_BRANCH_EXISTS == 1
        run: |
          git fetch --all --prune
          git checkout regenerate-readme
          git pull --no-rebase

      - name: Install WP-CLI
        run: |
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli-nightly.phar
          sudo mv wp-cli-nightly.phar /usr/local/bin/wp
          sudo chmod +x /usr/local/bin/wp

      - name: Regenerate README.md file
        run: |
          wp package install "wp-cli/scaffold-package-command:^2"
          wp scaffold package-readme --branch=${{ github.event.repository.default_branch }} --force .

      - name: Check if there are changes
        run: echo "CHANGES_DETECTED=$([[ -z $(git status --porcelain) ]] && echo "0" || echo "1")" >> $GITHUB_ENV

      - name: Commit changes
        if: env.CHANGES_DETECTED == 1
        run: |
          git add README.md
          git commit -m "Regenerate README file - $(date +'%Y-%m-%d')"
          git push origin regenerate-readme

      - name: Create pull request
        if: |
          env.CHANGES_DETECTED == 1 &&
          env.REMOTE_BRANCH_EXISTS == 0
        uses: repo-sync/pull-request@v2
        with:
          source_branch: regenerate-readme
          destination_branch: ${{ github.event.repository.default_branch }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: Regenerate README file
          pr_body: "**This is an automated pull-request**\n\nRefreshes the `README.md` file with the latest changes to the docblocks in the source code."
          pr_reviewer: schlessera
          pr_label: scope:documentation
